version: 1
disable_existing_loggers: false
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
root:
  level: INFO
  handlers: [console]
